<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LAPTOP-CC6D02LD" name="Default test" tests="2" failures="0" timestamp="22 Apr 2020 14:10:58 GMT" time="8.081" errors="0">
  <testcase name="@BeforeMethod setup" time="0.0" classname="com.testpack.PIMtest">
    <failure type="java.lang.Error" message="Unresolved compilation problem: 
	Syntax error, insert &amp;quot;}&amp;quot; to complete MethodBody
">
      <![CDATA[java.lang.Error: Unresolved compilation problem: 
	Syntax error, insert "}" to complete MethodBody

	at com.utils.WebEventListener.<init>(WebEventListener.java:56)
	at parentclass.Apputils.intilization(Apputils.java:64)
	at com.testpack.PIMtest.setup(PIMtest.java:31)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:514)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:215)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:589)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
    </failure>
  </testcase> <!-- @BeforeMethod setup -->
  <testcase name="@AfterMethod closeapp" time="0.0" classname="com.testpack.PIMtest">
    <skipped/>
  </testcase> <!-- @AfterMethod closeapp -->
  <testcase name="@BeforeMethod setup" time="0.0" classname="com.testpack.PIMtest">
    <skipped/>
  </testcase> <!-- @BeforeMethod setup -->
  <testcase name="@AfterMethod closeapp" time="0.0" classname="com.testpack.PIMtest">
    <skipped/>
  </testcase> <!-- @AfterMethod closeapp -->
  <testcase name="pimtest" time="0.002" classname="com.testpack.PIMtest">
    <skipped/>
  </testcase> <!-- pimtest -->
  <testcase name="Addemployeetest" time="0.003" classname="com.testpack.PIMtest">
    <skipped/>
  </testcase> <!-- Addemployeetest -->
</testsuite> <!-- Default test -->
